<?php

use Drupal\views\ViewExecutable;

function views_polyglot_views_post_execute(ViewExecutable $view) {
//dpm($view->polyglot==TRUE);
	if ($view->polyglot) {

		foreach ($view->filter as $id=>$handler) {
                        //dpm(is_callable(array($handler, 'polyglotPostExecute')));
			if (is_callable(array($handler, 'polyglotPostExecute'))) {
				$handler->polyglotPostExecute();
				
			}
		}	
	}


}

function views_polyglot_views_pre_execute(ViewExecutable $view) {

	if ($view->polyglot) {
dpm('pre_exe');
  $view->query->setLimit(0);
  $view->query->setOffset(0);	
	}


}



function views_polyglot_views_pre_render(ViewExecutable $view) {

	if ($view->polyglot) {

  $view->pager->total_items = count($view->result);
  $view->pager->updatePageInfo();	

  $item_per_page = $view->pager->getItemsPerPage();
  if ($item_per_page > 0) {
    $offset = $view->pager->getCurrentPage() * $item_per_page + $view->pager->getOffset();
dpm('pre_render' . $offset . '+' .$item_per_page);

  $view->result = array_slice($view->result, $offset, $item_per_page, false);
dpm($view->result);
  }
	}


}
